---


- hosts: 172.25.5.104
  become: true
  tasks:

  - name: Install apache2 and packages for Ubuntu
    apt:
      name: 
        - apache2
        - libapache2-mod-php
      state: latest
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

  - name: Install apache2 and packages for CentOS
    dnf:
      name: 
        - httpd
        - php
      state: latest
      update_cache; yes
    when: ansible_distribution == "CentOS"

  

